import * as THREE from "three";
import { groundMaterial as buildGround, type GroundMaterial, type SurfaceImages } from "./splat-material.js";

/**
 * Terrain surfaces: loading them, and handing them to the two things that
 * draw ground.
 *
 * The surfaces are generated by `scripts/generate-terrain.mjs` and committed;
 * see UNIVERSE.md for what each one is meant to be, one entry per biome
 * ("The world" for Furnace Nine's `ashworks`, "Other fronts" for anything
 * after it). This file is only concerned with getting them onto the GPU
 * correctly, which is a shorter list than it looks but every item on it is a
 * visible bug when it is wrong.
 *
 * A biome has several surfaces and a map paints with up to five of them;
 * which five is map data, so the ground material is built per map rather
 * than per biome. See splat-material.ts for how they are blended, and
 * packages/content/src/paint.ts for what a map stores.
 *
 * A glob rather than a name per biome, matching model-library.ts's own
 * reason: adding a biome or a surface is running the generator and adding a
 * map that asks for it, and nothing here has to know its name in advance.
 */
const FILES = import.meta.glob<string>("../assets/terrain/*.png", {
  eager: true,
  query: "?url",
  import: "default",
});

/** The generator's own account of what it wrote; see its header. */
const MANIFESTS = import.meta.glob<TerrainManifest>("../assets/terrain/terrain.json", {
  eager: true,
  import: "default",
});

interface SurfaceInfo {
  /** How many world tiles one repeat covers. */
  readonly repeat: number;
  /** How brightly this surface's glow channel emits; 0 for most. */
  readonly glow: number;
  /** Its average colour, for the minimap, which cannot sample a texture. */
  readonly colour: string;
}

type TerrainManifest = Record<
  string,
  { surfaces: Record<string, SurfaceInfo>; cliff: SurfaceInfo }
>;

const manifest: TerrainManifest = Object.values(MANIFESTS)[0] ?? {};

export interface TerrainBiome {
  readonly id: string;
  /**
   * The material for one map's ground.
   *
   * Per map, not per biome: it carries that map's paint and only the
   * surfaces that map uses. The caller owns it and must dispose it when the
   * match ends -- unlike the textures behind it, which are cached here for
   * the life of the process.
   */
  ground(options: { layers: readonly string[]; paint: Uint8Array; mapTiles: number }): GroundMaterial;
  /** For the instanced blocks that stand in for cliffs and spoil heaps. */
  readonly slag: THREE.MeshStandardMaterial;
  /** Average colour per surface, for the minimap. Keyed by surface name. */
  readonly colours: Readonly<Record<string, string>>;
  dispose(): void;
}

const pending = new Map<string, Promise<TerrainBiome>>();

/**
 * Load one biome's terrain, once per biome for the life of the process.
 *
 * A match's own biome is not known until a map is chosen, so this is awaited
 * when a match is about to start rather than at the menu -- see main.ts.
 * Decoding a dozen PNGs is not the hitch loading every biome up front at
 * startup would be as their number grows, and it is cheap enough on its own
 * that the setup screen's own load already covers it: the player is reading
 * a lobby, not staring at a blank frame.
 */
export function loadTerrain(biome: string): Promise<TerrainBiome> {
  let promise = pending.get(biome);
  if (!promise) {
    promise = build(biome);
    pending.set(biome, promise);
  }
  return promise;
}

/** A biome's file, by the name `generate-terrain.mjs` writes it as. */
function fileFor(biome: string, surface: string, map: "albedo" | "normal" | "orm"): string {
  const path = `../assets/terrain/${biome}_${surface}_${map}.png`;
  const url = FILES[path];
  if (!url) {
    throw new Error(
      `terrain: no '${map}' texture for '${biome}_${surface}' -- ` +
        "run scripts/generate-terrain.mjs, or check the map's biome and layers",
    );
  }
  return url;
}

/**
 * Decode one PNG to pixels.
 *
 * `createImageBitmap` rather than an `<img>` and a `<canvas>` alone because
 * it decodes off the main thread; the canvas is still needed afterwards,
 * because nothing in the platform reads pixels out of a bitmap directly.
 *
 * `premultiplyAlpha: "none"` and `colorSpaceConversion: "none"` are both
 * load-bearing: the alpha channels here are a height and a glow mask, not
 * transparency, and multiplying the colour by them would quietly destroy
 * both. The browser has no way to know that.
 */
async function pixels(url: string): Promise<ImageData> {
  const response = await fetch(url);
  if (!response.ok) throw new Error(`terrain: cannot read ${url} (${response.status})`);
  const bitmap = await createImageBitmap(await response.blob(), {
    premultiplyAlpha: "none",
    colorSpaceConversion: "none",
  });
  const canvas = new OffscreenCanvas(bitmap.width, bitmap.height);
  const context = canvas.getContext("2d", { willReadFrequently: true });
  if (!context) throw new Error("terrain: no 2d context to decode textures with");
  context.drawImage(bitmap, 0, 0);
  const data = context.getImageData(0, 0, bitmap.width, bitmap.height);
  bitmap.close();
  return data;
}

async function build(biome: string): Promise<TerrainBiome> {
  const entry = manifest[biome];
  if (!entry) {
    throw new Error(
      `terrain: biome '${biome}' is not in terrain.json -- ` +
        "add it to scripts/generate-terrain.mjs and run it",
    );
  }

  const names = Object.keys(entry.surfaces);
  const loaded = await Promise.all(
    names.map(async (name): Promise<SurfaceImages> => {
      const [albedo, normal, orm] = await Promise.all([
        pixels(fileFor(biome, name, "albedo")),
        pixels(fileFor(biome, name, "normal")),
        pixels(fileFor(biome, name, "orm")),
      ]);
      return { albedo, normal, orm, repeat: entry.surfaces[name].repeat, glow: entry.surfaces[name].glow };
    }),
  );
  const surfaces = new Map(names.map((name, i) => [name, loaded[i]]));

  const slag = await slagMaterial(biome);
  const colours = Object.fromEntries(names.map((name) => [name, entry.surfaces[name].colour]));
  const grounds = new Set<GroundMaterial>();

  return {
    id: biome,

    ground({ layers, paint, mapTiles }) {
      const images = layers.map((name) => {
        const surface = surfaces.get(name);
        if (!surface) {
          throw new Error(
            `terrain: biome '${biome}' has no surface '${name}' -- it has ${names.join(", ")}`,
          );
        }
        return surface;
      });
      const built = buildGround({ layers: images, paint, mapTiles });
      grounds.add(built);
      return {
        material: built.material,
        dispose() {
          grounds.delete(built);
          built.dispose();
        },
      };
    },

    slag,
    colours,

    dispose() {
      for (const ground of grounds) ground.dispose();
      grounds.clear();
      slag.map?.dispose();
      slag.normalMap?.dispose();
      slag.aoMap?.dispose();
      slag.dispose();
    },
  };
}

/**
 * The spoil heaps' material.
 *
 * An ordinary textured material, not a splat: the heaps are objects standing
 * on the ground rather than part of it, there is only ever one surface on
 * them, and they are instanced with a per-instance fog colour that a ground
 * shader has nowhere to put.
 */
async function slagMaterial(biome: string): Promise<THREE.MeshStandardMaterial> {
  const loader = new THREE.TextureLoader();
  const load = (url: string, srgb: boolean): Promise<THREE.Texture> =>
    new Promise((resolve, reject) => {
      loader.load(
        url,
        (texture) => {
          // Colour goes through the sRGB transfer; normals and packed ORM
          // data must not. Getting this backwards on a normal map produces
          // lighting that is subtly wrong everywhere and obviously wrong
          // nowhere.
          texture.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
          texture.wrapS = THREE.RepeatWrapping;
          texture.wrapT = THREE.RepeatWrapping;
          texture.anisotropy = 8;
          resolve(texture);
        },
        undefined,
        reject,
      );
    });

  const [albedo, normal, orm] = await Promise.all([
    load(fileFor(biome, "slag", "albedo"), true),
    load(fileFor(biome, "slag", "normal"), false),
    load(fileFor(biome, "slag", "orm"), false),
  ]);

  const material = new THREE.MeshStandardMaterial({
    map: albedo,
    normalMap: normal,
    aoMap: orm,
    roughnessMap: orm,
    metalnessMap: orm,
    roughness: 1,
    metalness: 1,
    // Per-instance colour carries the fog shade; see TerrainRenderer.
    color: 0xffffff,
    vertexColors: false,
    // Distance fog would lift these toward the horizon tone, and they are the
    // darkest thing in the scene by design.
    fog: false,
  });
  material.normalScale.set(1.1, 1.1);
  return material;
}

/**
 * The ground, as geometry with a baked-in macro tint.
 *
 * A surface that repeats a hundred times across a map reads as wallpaper no
 * matter how good it is. The paint layer answers most of that -- different
 * ground in different places is the strongest possible break in a repeat --
 * but a map is still mostly one surface, and the fix for that is variation
 * at a scale no texture can provide. The cheapest place to put it is the
 * vertices: a subdivided plane with per-vertex colour costs one attribute
 * and no shader work at all.
 *
 * The tint is not random. It darkens toward the spoil heaps, because that is
 * where the ash comes from -- so the ground tells you where the cover is
 * even through fog, and the variation looks like a consequence of the map
 * rather than like noise.
 */
export function groundGeometry(
  mapTiles: number,
  isBlocked: (tileX: number, tileY: number) => boolean,
): THREE.PlaneGeometry {
  // One vertex every few tiles. Enough to carry drifts, far short of enough to
  // matter to the vertex shader even on the largest map.
  const segments = Math.min(128, Math.max(16, Math.round(mapTiles / 6)));
  const geometry = new THREE.PlaneGeometry(mapTiles, mapTiles, segments, segments);
  geometry.rotateX(-Math.PI / 2);

  const position = geometry.getAttribute("position");
  const colours = new Float32Array(position.count * 3);
  const step = mapTiles / segments;

  for (let i = 0; i < position.count; i++) {
    // The plane is centred on the origin until the mesh is positioned, so shift
    // into tile space to ask the grid anything.
    const tileX = position.getX(i) + mapTiles / 2;
    const tileY = position.getZ(i) + mapTiles / 2;

    // How much spoil is within a few tiles. Sampled coarsely: this is a shading
    // hint, and reading every tile in the radius on a 1024 map would be four
    // million lookups for a gradient nobody could tell apart from this one.
    let nearby = 0;
    let taken = 0;
    const radius = Math.max(2, Math.round(step));
    for (let dy = -radius; dy <= radius; dy += Math.max(1, radius >> 1)) {
      for (let dx = -radius; dx <= radius; dx += Math.max(1, radius >> 1)) {
        taken++;
        if (isBlocked(Math.round(tileX + dx), Math.round(tileY + dy))) nearby++;
      }
    }
    const soot = taken > 0 ? nearby / taken : 0;

    // Broad drifts, so open ground is not uniform either.
    const drift = fbm2(tileX * 0.035, tileY * 0.035);

    // Strong, but not as strong as it was before the paint layer existed:
    // this now competes with real changes of material rather than being the
    // only thing standing between the player and a tiled floor.
    const shade = 1 - soot * 0.42 - drift * 0.34;
    colours[i * 3] = shade;
    colours[i * 3 + 1] = shade * 0.99;
    colours[i * 3 + 2] = shade * 0.96;
  }

  geometry.setAttribute("color", new THREE.BufferAttribute(colours, 3));
  return geometry;
}

/** Two octaves of value noise, in [0, 1). Enough for a drift. */
function fbm2(x: number, y: number): number {
  return value(x, y) * 0.65 + value(x * 2.3, y * 2.3) * 0.35;
}

function value(x: number, y: number): number {
  const ix = Math.floor(x);
  const iy = Math.floor(y);
  const fx = x - ix;
  const fy = y - iy;
  const sx = fx * fx * (3 - 2 * fx);
  const sy = fy * fy * (3 - 2 * fy);

  const a = hash(ix, iy);
  const b = hash(ix + 1, iy);
  const c = hash(ix, iy + 1);
  const d = hash(ix + 1, iy + 1);
  return (a + (b - a) * sx) * (1 - sy) + (c + (d - c) * sx) * sy;
}

function hash(x: number, y: number): number {
  let h = (x * 374761393 + y * 668265263) | 0;
  h = (h ^ (h >>> 13)) | 0;
  h = Math.imul(h, 1274126177) | 0;
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}
