import * as THREE from "three";
import ashfieldAlbedo from "../assets/terrain/ashfield_albedo.png";
import ashfieldNormal from "../assets/terrain/ashfield_normal.png";
import ashfieldOrm from "../assets/terrain/ashfield_orm.png";
import slagAlbedo from "../assets/terrain/slag_albedo.png";
import slagNormal from "../assets/terrain/slag_normal.png";
import slagOrm from "../assets/terrain/slag_orm.png";

/**
 * Terrain materials, and the loading of the textures behind them.
 *
 * The textures are generated by `scripts/generate-terrain.mjs` and committed;
 * see UNIVERSE.md for what each surface is meant to be. This file is only
 * concerned with getting them onto the GPU correctly, which is a shorter list
 * than it looks but every item on it is a visible bug when it is wrong.
 *
 * Imported as modules rather than fetched from a path. Vite then emits them
 * with a content hash and rewrites the URL relative to the document, which is
 * what makes them load from inside a packaged `app.asar` -- an absolute `/`
 * path resolves against the filesystem root there and silently loads nothing.
 */

/**
 * How many world tiles one repeat of a surface covers.
 *
 * The camera shows roughly 20 screen pixels per tile, and the textures are 512
 * across, so this is about 43 texture pixels per tile -- still twice what the
 * screen can resolve, and each doubling here halves how often the pattern
 * repeats across the view. The ground surface is pure organic noise precisely
 * so that this number can be pushed without a pattern lining up; see the note
 * in scripts/generate-terrain.mjs.
 */
const TILES_PER_REPEAT = 12;

export interface TerrainMaterials {
  /** For the ground plane. Sized per map; see `groundMaterial`. */
  groundMaterial(mapTiles: number): THREE.MeshStandardMaterial;
  /** For the instanced blocks that stand in for cliffs and spoil heaps. */
  readonly slag: THREE.MeshStandardMaterial;
  dispose(): void;
}

let pending: Promise<TerrainMaterials> | null = null;

/**
 * Load the terrain textures once, for the life of the process.
 *
 * Awaited at startup rather than when a match begins. Decoding six PNGs takes
 * long enough to be a visible hitch, and the moment it would land is exactly
 * when the player has just pressed Start.
 */
export function loadTerrain(): Promise<TerrainMaterials> {
  pending ??= build();
  return pending;
}

async function build(): Promise<TerrainMaterials> {
  const loader = new THREE.TextureLoader();

  const load = (url: string, srgb: boolean): Promise<THREE.Texture> =>
    new Promise((resolve, reject) => {
      loader.load(
        url,
        (texture) => {
          // Colour goes through the sRGB transfer; normals and packed ORM data
          // must not. Getting this backwards on a normal map produces lighting
          // that is subtly wrong everywhere and obviously wrong nowhere.
          texture.colorSpace = srgb ? THREE.SRGBColorSpace : THREE.NoColorSpace;
          texture.wrapS = THREE.RepeatWrapping;
          texture.wrapT = THREE.RepeatWrapping;
          // The ground is seen at a shallow isometric angle, which is the exact
          // case trilinear filtering handles worst: without anisotropy the
          // floor smears into grey mush a third of the way up the screen.
          texture.anisotropy = 8;
          resolve(texture);
        },
        undefined,
        reject,
      );
    });

  const [ra, rn, ro, sa, sn, so] = await Promise.all([
    load(ashfieldAlbedo, true),
    load(ashfieldNormal, false),
    load(ashfieldOrm, false),
    load(slagAlbedo, true),
    load(slagNormal, false),
    load(slagOrm, false),
  ]);

  const slag = new THREE.MeshStandardMaterial({
    map: sa,
    normalMap: sn,
    aoMap: so,
    roughnessMap: so,
    metalnessMap: so,
    roughness: 1,
    metalness: 1,
    // Per-instance colour carries the fog shade; see TerrainRenderer.
    color: 0xffffff,
    vertexColors: false,
    // Distance fog would lift these toward the horizon tone, and they are the
    // darkest thing in the scene by design.
    fog: false,
  });
  slag.normalScale.set(1.1, 1.1);

  const groundCache = new Map<number, THREE.MeshStandardMaterial>();

  return {
    groundMaterial(mapTiles: number): THREE.MeshStandardMaterial {
      const cached = groundCache.get(mapTiles);
      if (cached) return cached;

      // Cloned per map size, because `repeat` lives on the texture rather than
      // on the material -- one shared texture would mean the last map loaded
      // decided the tiling for every other.
      const repeat = mapTiles / TILES_PER_REPEAT;
      const albedo = ra.clone();
      const normal = rn.clone();
      const orm = ro.clone();
      for (const texture of [albedo, normal, orm]) {
        texture.repeat.set(repeat, repeat);
        texture.needsUpdate = true;
      }

      const material = new THREE.MeshStandardMaterial({
        map: albedo,
        normalMap: normal,
        aoMap: orm,
        roughnessMap: orm,
        metalnessMap: orm,
        roughness: 1,
        metalness: 1,
        // The macro tint that breaks up the repeat lives in the geometry; see
        // `groundGeometry`.
        vertexColors: true,
      });
      material.normalScale.set(0.8, 0.8);

      groundCache.set(mapTiles, material);
      return material;
    },

    slag,

    dispose() {
      for (const texture of [ra, rn, ro, sa, sn, so]) texture.dispose();
      for (const material of groundCache.values()) {
        material.map?.dispose();
        material.normalMap?.dispose();
        material.aoMap?.dispose();
        material.dispose();
      }
      groundCache.clear();
      slag.dispose();
    },
  };
}

/**
 * The ground, as geometry with a baked-in macro tint.
 *
 * A texture that repeats 128 times across a map reads as wallpaper no matter
 * how good it is. The fix is variation at a scale the texture cannot provide,
 * and the cheapest place to put it is the vertices: a subdivided plane with per
 * vertex colour costs one attribute and no shader work at all.
 *
 * The tint is not random. It darkens toward the spoil heaps, because that is
 * where the ash comes from -- so the ground tells you where the cover is even
 * through fog, and the variation looks like a consequence of the map rather
 * than like noise.
 */
export function groundGeometry(
  mapTiles: number,
  isBlocked: (tileX: number, tileY: number) => boolean,
): THREE.PlaneGeometry {
  // One vertex every few tiles. Enough to carry drifts, far short of enough to
  // matter to the vertex shader even on the largest map.
  const segments = Math.min(128, Math.max(16, Math.round(mapTiles / 6)));
  const geometry = new THREE.PlaneGeometry(mapTiles, mapTiles, segments, segments);
  geometry.rotateX(-Math.PI / 2);

  const position = geometry.getAttribute("position");
  const colours = new Float32Array(position.count * 3);
  const step = mapTiles / segments;

  for (let i = 0; i < position.count; i++) {
    // The plane is centred on the origin until the mesh is positioned, so shift
    // into tile space to ask the grid anything.
    const tileX = position.getX(i) + mapTiles / 2;
    const tileY = position.getZ(i) + mapTiles / 2;

    // How much spoil is within a few tiles. Sampled coarsely: this is a shading
    // hint, and reading every tile in the radius on a 1024 map would be four
    // million lookups for a gradient nobody could tell apart from this one.
    let nearby = 0;
    let taken = 0;
    const radius = Math.max(2, Math.round(step));
    for (let dy = -radius; dy <= radius; dy += Math.max(1, radius >> 1)) {
      for (let dx = -radius; dx <= radius; dx += Math.max(1, radius >> 1)) {
        taken++;
        if (isBlocked(Math.round(tileX + dx), Math.round(tileY + dy))) nearby++;
      }
    }
    const soot = taken > 0 ? nearby / taken : 0;

    // Broad drifts, so open ground is not uniform either.
    const drift = fbm2(tileX * 0.035, tileY * 0.035);

    // Strong on purpose. This is what has to break up a texture repeating a
    // hundred times across a map, and it is competing with a regular grid.
    const shade = 1 - soot * 0.55 - drift * 0.5;
    colours[i * 3] = shade;
    colours[i * 3 + 1] = shade * 0.99;
    colours[i * 3 + 2] = shade * 0.96;
  }

  geometry.setAttribute("color", new THREE.BufferAttribute(colours, 3));
  return geometry;
}

/** Two octaves of value noise, in [0, 1). Enough for a drift. */
function fbm2(x: number, y: number): number {
  return value(x, y) * 0.65 + value(x * 2.3, y * 2.3) * 0.35;
}

function value(x: number, y: number): number {
  const ix = Math.floor(x);
  const iy = Math.floor(y);
  const fx = x - ix;
  const fy = y - iy;
  const sx = fx * fx * (3 - 2 * fx);
  const sy = fy * fy * (3 - 2 * fy);

  const a = hash(ix, iy);
  const b = hash(ix + 1, iy);
  const c = hash(ix, iy + 1);
  const d = hash(ix + 1, iy + 1);
  return (a + (b - a) * sx) * (1 - sy) + (c + (d - c) * sx) * sy;
}

function hash(x: number, y: number): number {
  let h = (x * 374761393 + y * 668265263) | 0;
  h = (h ^ (h >>> 13)) | 0;
  h = Math.imul(h, 1274126177) | 0;
  return ((h ^ (h >>> 16)) >>> 0) / 4294967296;
}
